"""create tables

Revision ID: ad642e3a9d36
Revises: 68c67f74dc7e
Create Date: 2023-10-27 14:08:46.339008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad642e3a9d36'
down_revision = '68c67f74dc7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
